name: Create release with tag

on:
  push:
    tags: ['*']

jobs:
  create-release:
    name: Create release with tag
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for tag ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
